name: WOOD PARK DENTAL
favicon: null
layout_spectrum: 0.44453
typography_spectrum: 0.7043929158244282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.469101618276909
  lightness: 0.07810896937735379
  saturation: 0.15127603011205792
  rhythmicContrast: 0.28145417873747647
purpose: []
